name: Create Draft Release on Pull Request

on:
  pull_request:
    types: [opened]

permissions:
  contents: write

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

        with:
          draft: true

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Create draft release
        run: gh release create --draft "pr-${{ github.event.pull_request.number }}" --notes "Draft release for PR #${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
