name: Create Draft Release on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  create_release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: create_release
        
      - name: Set release details
        run: |
          gh release create --draft "pr-${{ github.event.pull_request.number }}" --notes "Draft release for PR #${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
